In [104]:
import numpy as np

In [164]:
!head cric_data.tsv

	Sachin Tendulkar	Rahul Dravid	India
0	100	78	342
1	11	62	191
2	8	85	252
3	71	24	307
4	104	17	229
5	18	104	246
6	8	76	226
7	86	74	288
8	12	60	216


In [106]:
cric_data = np.loadtxt ("cric_data.tsv", skiprows=1)
cric_data

array([[  0., 100.,  78., 342.],
       [  1.,  11.,  62., 191.],
       [  2.,   8.,  85., 252.],
       [  3.,  71.,  24., 307.],
       [  4., 104.,  17., 229.],
       [  5.,  18., 104., 246.],
       [  6.,   8.,  76., 226.],
       [  7.,  86.,  74., 288.],
       [  8.,  12.,  60., 216.],
       [  9.,  85.,  12., 224.],
       [ 10.,  18.,  63., 161.],
       [ 11.,   4., 107., 276.],
       [ 12.,   7.,  76., 283.],
       [ 13.,  37.,   4., 297.],
       [ 14.,  14.,   5., 139.],
       [ 15.,   0.,  33., 224.],
       [ 16.,   4.,   7., 178.],
       [ 17.,   0.,   0.,   0.],
       [ 18.,  21.,  36., 193.],
       [ 19.,   1.,  66., 231.],
       [ 20.,  62.,   0., 134.],
       [ 21.,   0., 123., 246.],
       [ 22., 138.,  39., 299.],
       [ 23.,  38.,   9., 242.],
       [ 24.,   2.,  11., 214.],
       [ 25.,  46.,  14., 152.],
       [ 26.,  65.,   0., 104.],
       [ 27.,   0.,   0.,   4.],
       [ 28.,  39.,  26., 155.],
       [ 29.,  48.,   4., 168.],
       [ 3

In [107]:
cric_data.shape

(225, 4)

In [108]:
cric_data1 = cric_data [:, [1, 2, 3]]


In [109]:
cric_data1.shape

(225, 3)

### Find mean,median,IQR for Sachin, Dravid and India

In [110]:
sachin = cric_data1 [:, 0]
dravid = cric_data1 [:, 1]
india = cric_data1 [:, 2]

In [111]:
def stats (col):
    print ("Mean", np.mean(col))
    print ("Median", np.median (col))
    print ("IQR", np.percentile (col, 75) - np.percentile (col, 25))

In [112]:
stats (sachin)

Mean 39.87555555555556
Median 27.0
IQR 57.0


In [113]:
stats (dravid)

Mean 32.062222222222225
Median 22.0
IQR 46.0


In [114]:
stats (india)

Mean 220.79555555555555
Median 216.0
IQR 98.0


In [115]:
all_mean = np.mean (cric_data1, axis=0 )
all_mean

array([ 39.87555556,  32.06222222, 220.79555556])

In [116]:
all_median = np.median (cric_data1, axis=0 )
all_median

array([ 27.,  22., 216.])

In [117]:
all_IQR = np.percentile (cric_data1, 75,  axis=0 ) - np.percentile (cric_data1, 25, axis=0)
all_IQR

array([57., 46., 98.])

### Compute histogram of Sachin Score with 10 bin

In [118]:
np.histogram (sachin)

(array([99, 36, 28, 16, 11, 17,  8,  8,  1,  1]),
 array([  0. ,  18.6,  37.2,  55.8,  74.4,  93. , 111.6, 130.2, 148.8,
        167.4, 186. ]))

In [119]:
np.histogram (sachin , bins=10 )

(array([99, 36, 28, 16, 11, 17,  8,  8,  1,  1]),
 array([  0. ,  18.6,  37.2,  55.8,  74.4,  93. , 111.6, 130.2, 148.8,
        167.4, 186. ]))

In [120]:
np.histogram (dravid)

(array([90, 43, 20, 30, 21, 11,  7,  0,  1,  2]),
 array([  0. ,  15.3,  30.6,  45.9,  61.2,  76.5,  91.8, 107.1, 122.4,
        137.7, 153. ]))

### Find mean of Sachin's score grouped by 25 matches

In [121]:
sachin.shape

(225,)

In [122]:
sachin_by_25 = sachin.reshape (9, 25)

In [123]:
sachin.reshape(9,25).shape

(9, 25)

In [124]:
np.mean (sachin_by_25 , axis=1)

array([33.96, 49.4 , 38.48, 40.16, 39.36, 38.2 , 44.6 , 39.52, 35.2 ])

### Find mean of Sachin's score where he has scored century

In [125]:
np.mean(sachin [sachin >= 100])


125.0

### Find mean of sachin's score when dravid has scored less than 10

In [126]:
np.mean(sachin [dravid < 10])

40.74285714285714

### Find mean of Sachins score for which quartile India's score falls in

In [127]:
qrs = np.percentile (india, [25, 50, 75, 100])
qrs

array([175., 216., 273., 499.])

In [128]:
## If India's scored <= 175 then sachin's average is.......
## If India's scored <= 216 then sachin's average is.....
## <= 273
## <= 499

In [129]:
sachin.shape

(225,)

In [130]:
qrs.shape

(4,)

In [131]:
qrs = qrs.reshape(4,1)

In [132]:
indices = india < qrs

In [133]:
indices.shape

(4, 225)

In [134]:
sachin [indices [0, :]]

array([18., 14.,  0., 62., 46., 65.,  0., 39., 48.,  3., 11., 65., 27.,
       28.,  3.,  4., 15., 40.,  5.,  8., 89.,  0.,  0.,  1.,  0.,  0.,
       81., 13.,  2., 36., 12., 19.,  0.,  6., 35.,  0., 44.,  3., 47.,
       17., 35., 33.,  7.,  9.,  2., 11., 17.,  1., 10.,  0., 23.,  1.,
        2., 25.,  0.])

In [135]:
for i in range (4):
    print (i, np.mean(sachin [indices[i]]))


0 19.672727272727272
1 28.18018018018018
2 31.688622754491018
3 39.799107142857146


### For every match find out who has scored more - Sachin or Dravid

In [136]:
snd = cric_data1 [:, 0:2] 

In [137]:
is_dravid_higher = np.argmax (snd, axis=1) 

In [138]:
np.sum (is_dravid_higher)

106

In [139]:
print ("Fraction of dravid scoring higher", np.sum(is_dravid_higher)/225)

Fraction of dravid scoring higher 0.4711111111111111


In [140]:
who_is_higher = np.where( is_dravid_higher == 0, 'Sachin', 'Dravid')
who_is_higher

array(['Sachin', 'Dravid', 'Dravid', 'Sachin', 'Sachin', 'Dravid',
       'Dravid', 'Sachin', 'Dravid', 'Sachin', 'Dravid', 'Dravid',
       'Dravid', 'Sachin', 'Sachin', 'Dravid', 'Dravid', 'Sachin',
       'Dravid', 'Dravid', 'Sachin', 'Dravid', 'Sachin', 'Sachin',
       'Dravid', 'Sachin', 'Sachin', 'Sachin', 'Sachin', 'Sachin',
       'Sachin', 'Sachin', 'Dravid', 'Dravid', 'Sachin', 'Dravid',
       'Dravid', 'Sachin', 'Dravid', 'Sachin', 'Sachin', 'Sachin',
       'Sachin', 'Dravid', 'Sachin', 'Dravid', 'Dravid', 'Sachin',
       'Dravid', 'Sachin', 'Dravid', 'Dravid', 'Dravid', 'Dravid',
       'Sachin', 'Dravid', 'Sachin', 'Sachin', 'Dravid', 'Dravid',
       'Dravid', 'Sachin', 'Dravid', 'Sachin', 'Sachin', 'Sachin',
       'Sachin', 'Dravid', 'Sachin', 'Dravid', 'Dravid', 'Sachin',
       'Sachin', 'Dravid', 'Dravid', 'Sachin', 'Dravid', 'Dravid',
       'Sachin', 'Dravid', 'Dravid', 'Dravid', 'Dravid', 'Dravid',
       'Dravid', 'Sachin', 'Sachin', 'Sachin', 'Dravid', 'Sach

### How many runs sachin scores on average after scoring x runs

In [142]:
x_arr = np.arange (0, 101, 5)

In [153]:
x_arr = x_arr.reshape(x_arr.shape[0],1)

In [154]:
indices = (sachin >= x_arr)

In [155]:
indices.shape

(21, 225)

In [156]:
sachin [indices[1,:]]

array([100.,  11.,   8.,  71., 104.,  18.,   8.,  86.,  12.,  85.,  18.,
         7.,  37.,  14.,  21.,  62., 138.,  38.,  46.,  65.,  39.,  48.,
       141.,  62.,  12.,  41.,  11., 186.,  11.,  27.,  27.,  51.,  18.,
        32., 146.,   5.,  45., 141.,  12.,  65.,  27.,   7.,  16.,  28.,
         6., 123., 120.,   7.,  81.,  54., 122.,  14., 100.,  15.,  57.,
        99.,  37.,  38.,  32.,  21.,  32.,  40.,   5.,   8.,   5.,  50.,
        30.,  37.,  89.,  98.,  83.,  93.,  52., 152.,   8.,  93.,  45.,
        26.,  16.,  47.,  89.,  53.,  16.,  81.,  14.,  78.,   6., 105.,
       122.,   9.,   8.,  28.,  35.,  69.,  13.,  97.,  93.,  36.,  39.,
        29.,  12.,  19.,  34., 100.,  44.,  82.,  79.,   6.,   9.,   8.,
        23.,  93.,  35.,  63.,  74.,   8., 117.,  39.,  49.,  64.,  43.,
        72.,   5.,  17.,  65.,  20., 141.,  28.,  44.,  27.,  60.,  68.,
       139.,  31.,  44.,  47.,   6.,  17.,  35.,  88., 114.,   7., 127.,
        45.,  33., 110., 146.,   7.,  25.,   9.,  1

In [158]:
for i in range (x_arr.shape [0]):
    print ( x_arr[i], np.mean(sachin[indices[i, :]])-x_arr [i] )

[0] [39.87555556]
[5] [45.61363636]
[10] [47.48026316]
[15] [47.45255474]
[20] [46.824]
[25] [44.10084034]
[30] [45.13461538]
[35] [43.24742268]
[40] [44.05882353]
[45] [43.41558442]
[50] [43.98529412]
[55] [42.31746032]
[60] [38.67213115]
[65] [37.65454545]
[70] [37.08163265]
[75] [34.34782609]
[80] [30.75]
[85] [28.65]
[90] [27.4]
[95] [26.43333333]
[100] [25.]


### How many match does sachin take to score first 1000, next 1000 runs

In [159]:
sachin

array([100.,  11.,   8.,  71., 104.,  18.,   8.,  86.,  12.,  85.,  18.,
         4.,   7.,  37.,  14.,   0.,   4.,   0.,  21.,   1.,  62.,   0.,
       138.,  38.,   2.,  46.,  65.,   0.,  39.,  48., 141.,  62.,  12.,
         1.,  41.,  11.,   3., 186.,  11.,  27.,  27.,  51.,  18.,  32.,
       146.,   5.,  45., 141.,  12.,  65.,  27.,   7.,  16.,   2.,  28.,
         6., 123., 120.,   7.,   3.,   0.,  81.,   2.,  54., 122.,   4.,
        14.,   0., 100.,  15.,   0.,  57.,  99.,  37.,  38.,  32.,  21.,
        32.,  40.,   0.,   5.,   8.,   5.,   0.,  50.,  30.,  37.,  89.,
         4.,  98.,  83.,  93.,   0.,  52., 152.,   1.,   8.,  93.,  45.,
        26.,   0.,   1.,   0.,  16.,  47.,  89.,   3.,   1.,  53.,  16.,
         0.,  81.,  14.,  78.,   6., 105., 122.,   9.,   8.,  28.,  35.,
        69.,  13.,  97.,  93.,   2.,  36.,  39.,   2.,  29.,  12.,  19.,
        34.,   2., 100.,  44.,  82.,   0.,  79.,   6.,   9.,   8.,  23.,
        93.,  35.,  63.,  74.,   8., 117.,  39.,  4

In [166]:
sachin_cumsum = np.cumsum (sachin)

In [168]:
np.histogram (sachin_cumsum, bins = np.arange (0, 10000, 1000))

(array([29, 18, 26, 25, 26, 26, 23, 22, 30]),
 array([   0, 1000, 2000, 3000, 4000, 5000, 6000, 7000, 8000, 9000]))